url: "https://markellekelly.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Markelle Kelly" # the name of your site, e.g. ACME Corp.
description: "personal website for Markelle Kelly"
