url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Home" # the name of your site, e.g. ACME Corp.
# description: "Doctoral student at Zhejiang University"
# theme: academic-jekyll-theme
