menu:
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/assets/markelle_cv.pdf'}

social:
- {icon: 'github', link: 'https://github.com/markellekelly'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/markellekelly/'}