menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'github', link: 'https://github.com/markellekelly'}
- {icon: 'twitter', link: 'https://twitter.com/markellekelly'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/markellekelly/'}